spring.application.name=ai-agent-resume-screening-system

spring.servlet.multipart.enabled=true

spring.ai.google.genai.chat.model=gemini-3.1-flash-lite

spring.ai.google.genai.embedding.text.model=gemini-embedding-2

spring.ai.google.genai.api-key=${GENAI_API_KEY}
spring.ai.google.genai.embedding.api-key=${GENAI_API_KEY}