spring.application.name=ai-agent-resume-screening-system

spring.servlet.multipart.enabled=true

spring.ai.google.genai.api-key=${GOOGLE_GENAI_API_KEY}
spring.ai.google.genai.embedding.api-key=${GOOGLE_GENAI_API_KEY}